import type { Metadata } from "next";
import SidebarContextProvider from "@/Context/SidebarContext";
import Sidebar from "@/components/dashboard/sidebar/Sidebar";
import { CirclePlus, Kanban, PlaneTakeoff } from "lucide-react";
import SidebarItem from "@/components/dashboard/sidebar/SidebarItem";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/AuthOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionData = await getServerSession(authOptions);
  // console.log(sessionData?.user);

  const navigations = [
    {
      path: "flights",
      icon: <PlaneTakeoff size={20} />,
      text: "All Flights",
    },
    {
      path: "add-movie",
      icon: <CirclePlus size={20} />,
      text: "Add Movie",
    },
    {
      path: "manage-movie",
      icon: <Kanban size={20} />,
      text: "Manage Movie",
    },
  ];
  return (
    <>
      <SidebarContextProvider>
        <div className="flex relative">
          <Sidebar>
            {navigations.map((nav, i) => (
              <SidebarItem
                key={i}
                path={nav.path}
                icon={nav.icon}
                text={nav.text}
              />
            ))}
          </Sidebar>
          <main className="flex-1 pl-20 md:pl-6 p-6 max-h-screen overflow-y-auto">
            {children}
          </main>
        </div>
      </SidebarContextProvider>
    </>
  );
}
